[[runs]]
roots = [""]

[[runs.tools]]
script = "CodeQL"
config = "Python"

[[runs.tools]]
script = "Semgrep"
config = "Python"

[[runs.tools]]
script = "Bearer"
config = "Python"

[[runs.tools]]
script = "Bandit"
config = "Python"

[[runs.tools]]
script = "Snyk"
config = "Python"

